[manager]
ratio          = [ 1, 3, 3 ]
sort_by        = "size"
sort_sensitive = true
sort_reverse   = true
sort_dir_first = true
linemode       = "size"
show_hidden    = false
show_symlink   = true

[opener]
markdown = [
  { run = 'glow -p "$@"', block = true, desc = "Open with Glow"},
  { run = 'nvim "$@"', block = true, desc = "Edit with Nvim" }
]
pdf = [
  { run = 'zathura "$@"', block = true, desc = "Zathura" }
]

edit = [
	{ run = '$EDITOR "$@"', block = true},
]
open = [
	{ run = 'xdg-open "$@"',                desc = "Open", for = "linux" },
	{ run = 'open "$@"',                    desc = "Open", for = "macos" },
]
reveal = [
	{ run = 'open -R "$1"',                          desc = "Reveal"},
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF"},
]
extract = [
	{ run = 'unar "$1"', desc = "Extract here"},
]
play = [
	{ run = 'mpv "$@"', orphan = true},
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info"},
  # { run = 'iina "$@"', orphan = true }
]

[preview]
image           = true
pdf             = true
tab_size        = 2
max_width       = 2000
max_height      = 2600
cache_dir       = ""
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[open]
rules = [
  { name = "*.md", use = "markdown" },
  { name = "*.pdf", use = "pdf" }
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { name = "*.pdf", run = "pdf" },
  { name = "*.jpg", run = "image" },
  { name = "*.png", run = "image" },
]

